# Generated by Django 4.1.3 on 2022-11-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_diseasetype_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pathogen', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=140)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.diseasetype')),
            ],
        ),
    ]
