# Generated by Django 4.1.3 on 2022-11-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('population', models.PositiveBigIntegerField()),
            ],
        ),
    ]
