# Generated by Django 4.1.3 on 2022-11-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
    ]
