# Generated by Django 4.1.3 on 2022-11-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_enc', models.DateField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.disease')),
            ],
        ),
        migrations.AddConstraint(
            model_name='discover',
            constraint=models.UniqueConstraint(fields=('cname', 'disease_code'), name='unique_cname_disease_code_combination'),
        ),
    ]
