# Generated by Django 4.1.3 on 2022-11-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_doctor_publicservant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.diseasetype')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.doctor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='specialize',
            constraint=models.UniqueConstraint(fields=('disease_type_id', 'email'), name='unique_id_email_combination'),
        ),
    ]
