# Generated by Django 4.1.3 on 2022-11-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_specialize_specialize_unique_id_email_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deaths', models.PositiveIntegerField()),
                ('total_patients', models.PositiveIntegerField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.disease')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.publicservant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('email', 'cname', 'disease_code'), name='unique_email_cname_disease_code_combination'),
        ),
    ]
